### ISSUE TITLE
Runtime issues on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [luigifcruz/CyberRadio#1]
Hey
I have some weird issues on macOS.
1- When I do `fbs run` and try to turn on the SDRPlay, it gives me an error:
`libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access`
But pressing the `ON` works. Now when I play with the UI, it crashes randomly without any errors. For example I tried to tune to different stations, but the app suddenly crashed. The last log was `[DEMOD] Starting Demodulator`
This is random. Sometimes after pressing the `ON` this happens.

The above random crashes happen to RTL SDR V3 and LimeSDR Mini as well (I just don't get the `darwin_claim_interface` error in this case)

2- I tested the app with AirSpy R2 this time. I have 4 devices shown in the menu: built-in Apple mic, two Soundflower options, and AIRSPY. Every time I select AIRSPY (last option in the menu), it automatically chooses the 3rd item (which is soundflower).
This is what logs look like:
```
[DEMOD] Activating AIRSPY [573064dc:312724c1] device.
[DEMOD] Activating ma++ ingalls for Cycling '74: Soundflower (64ch) device.
```
It actually happens after around 0.5-1 second (for a moment AIRSPY is selected but changes back to the other item in the menu)
This only happens when I select the last item (AIRSPY). And interestingly this does not happen with SDRPlay.
So I can't even use it.

I am using 3.7.5 on  macOS 10.15.2 with Soapy 0.8.0

**Comment by luigifcruz** [comment]
Hey, thanks for reporting these issues. I should fix them as soon as possible.

**Comment by luigifcruz** [comment]
I reproduced the random crashes on macOS Catalina. The Crash Report suggests there is some kind of Bad Memory Access made by PyAudio. I couldn't pinpoint the point of failure so I implemented some further sanitization of the audio output. This seems to have solved the problem for me. Please @mehdideveloper, report if this error is still happening. 

The `libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access` seems to be related to the SDRPlay toolkit since this doesn't happen with other radios. 

Further investigating the bug number two...

**Comment by mehdideveloper** [comment]
It still crashes. I found 2 other ways to crash:
1- Enter 2 frequencies one after another. For example tune to 97 and then 97.3
2- Power On, Power Off and Power On again. 

I tested these with RTL SDR V3

**Comment by mehdideveloper** [comment]
FYI I reproduced this on another Mac system to make sure it wasn't related to my specific system setup

**Comment by luigifcruz** [comment]
I found a stability problem with Numba on the macOS Catalina and ditched completely PyAudio for a more modern package (sounddevice). It seems to have improved considerably the crashes. I also disabled temporarily Numba on macOS. These fixes require a patched version of radio-core.

**Comment by mehdideveloper** [comment]
Just tested it with RTL SDR again. It's much more stable now.
I got another crash but it may not be very easy to reproduce:
Playing with the On/Off and FM/AM buttons (clicking them randomly in no particular order) made another crash:

```
Crashed Thread:        21  com.apple.audio.IOThread.client

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)

```

**Comment by luigifcruz** [comment]
Thanks for testing it! I reproduced this crash a couple of times. I'm not 100% sure of what is causing this.

**Comment by luigifcruz** [comment]
About Bug 2: The Airspy One is not currently supported by CyberRadio. When you select the device, it tries to enabled the device with an incompatible sample rate. This causes an exception and fallback to the following device. Support to the Airspy One will be added in the next commit.

**Comment by luigifcruz** [comment]
There was also an inconsistency with the AirSpy One's SoapySDR module. The current device listing  method can't find an AirSpy device if it's being used. I implemented the same method used by the AirSpy HF+ and submitted a Pull Request.

**Comment by luigifcruz** [comment]
I tracked down the remaining crashes and OpenBLAS (numpy's dependency) seems to be crashing at `dgetrf_parallel`. Are you running which version of macOS?

**Comment by mehdideveloper** [comment]
latest. 10.15.2

**Comment by luigifcruz** [comment]
Closing this issue since many things have changed. Please, reopen if this behaviour continues.
